In [1]:
from __future__ import print_function

# Import MNIST data
#from tensorflow.examples.tutorials.mnist import input_data
#mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

import tensorflow as tf

In [2]:
import numpy as np
data_X = np.zeros((100000,2))
data_y = np.zeros((100000,1))
import random

for i in range(data_X.shape[0]):
    data_X[i,0] = random.uniform(0, 1)
    data_X[i,1] = random.uniform(0, 1)
    if(data_X[i,0] >= 0.5 and data_X[i,1]>=0.5):
        data_y[i] = 1
    else:
        data_y[i] = 0
        
testx = np.zeros((100,2))
testy = np.zeros((100,1))
import random

for i in range(testx.shape[0]):
    testx[i,0] = random.uniform(0, 1)
    testx[i,1] = random.uniform(0, 1)
    if(testx[i,0] >= 0.5 and testx[i,1]>=0.5):
        testy[i] = 1
    else:
        testy[i] = 0


In [2]:
import numpy as np
data = np.loadtxt("Skin_NonSkin.txt")

In [4]:
import random

In [84]:
X = data[:,:3]/255.0
y = data[:,3]
y[y==2] = 0
index = random.sample(range(X.shape[0]),X.shape[0])
X = X[index]
y = y[index]
X_train = X[:int(X.shape[0]*70/100.0)]
y_train = y[:int(X.shape[0]*70/100.0)]
X_test = X[int(X.shape[0]*70/100.0):]
y_test = y[int(X.shape[0]*70/100.0):]
print(X_train.shape)
print(y_train.shape)

(171539, 3)
(171539,)


In [85]:
print(np.min(X_train))

0.0


In [86]:
import numpy as np
# Parameters
learning_rate = 0.001
num_steps = 10000
batch_size = 2000
display_step = 1000

# Network Parameters
n_hidden_1 = 2 #1st layer number of neurons
n_hidden_2 = 15 #2nd layer number of neurons
num_input = 3 # MNIST data input (img shape: 28*28)
num_classes = 1 # MNIST total classes (0-9 digits)

# initialize intervals for via
# [0,1] since sigmoid is used
#input_interval = np.zeros((2,num_input))
#input_interval[1,:] = input_interval[1,:] + 1
#input_interval[1,0] = 1
#input_interval[1,1] = 0.4
"""
input_interval = []
for i in range(num_input):
    input_interval.append([(0,255)])
input_interval = np.array(input_interval)
"""

#h1_interval = np.zeros((2,n_hidden_1))
#h1_interval[1,:] = h1_interval[1,:] + 1
"""
for i in range(n_hidden_1):
    h1_interval.append([0,1])
h1_interval = np.array(h1_interval)  
"""
#h2_interval = np.zeros((2,n_hidden_2))
#h2_interval[1,:] = h2_interval[1,:] + 1
"""
h2_interval = []
for i in range(n_hidden_2):
    h2_interval.append([(0,1)])
h2_interval = np.array(h2_interval)
"""

#out_interval = np.zeros((2,num_classes))
#out_interval[1,:] = out_interval[1,:] + 1
"""
out_interval = []
for i in range(num_classes):
    out_interval.append([(0,1)])
out_interval = np.array(out_interval)
"""

# tf Graph input
X = tf.placeholder("float", [None, num_input])
Y = tf.placeholder("float", [None, num_classes])

In [87]:
# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([num_input, n_hidden_1])),
    #'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_1, num_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    #'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([num_classes]))
}

In [88]:
# Create model
def neural_net(x):
    # Hidden fully connected layer with 256 neurons
    layer_1 = tf.sigmoid(tf.add(tf.matmul(x, weights['h1']), biases['b1']))
    # Hidden fully connected layer with 256 neurons
    #layer_2 = tf.sigmoid(tf.add(tf.matmul(layer_1, weights['h2']), biases['b2']))
    # Output fully connected layer with a neuron for each class
    out_layer = tf.sigmoid(tf.matmul(layer_1, weights['out']) + biases['out'])
    return out_layer

In [89]:
# Construct model
logits = neural_net(X)

# Define loss and optimizer
#loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y))
loss = -(Y * tf.log(logits) + (1 - Y) * tf.log( 1 - logits))
loss_op = tf.reduce_mean(tf.reduce_sum(loss, reduction_indices=[1]))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)

# Evaluate model (with test logits, for dropout to be disabled)
#correct_pred = tf.equal(tf.argmax(logits, 1), tf.argmax(Y, 1))
correct_pred = tf.equal(tf.greater_equal(logits, 0.5), tf.greater_equal(Y, 0.5))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

In [90]:
import random
def next_batch(batch_size):
    index = random.sample(range(X_train.shape[0]), batch_size)
    return X_train[index],y_train[index].reshape(-1,1)

In [91]:
# Start training
with tf.Session() as sess:

    # Run the initializer
    sess.run(init)

    for step in range(1, num_steps+1):
        batch_x, batch_y = next_batch(batch_size)
        # Run optimization op (backprop)
        sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
        if step % display_step == 0 or step == 1:
            # Calculate batch loss and accuracy
            loss, acc = sess.run([loss_op, accuracy], feed_dict={X: batch_x,
                                                                 Y: batch_y})
            print("Step " + str(step) + ", Minibatch Loss= " + \
                  "{:.4f}".format(loss) + ", Training Accuracy= " + \
                  "{:.3f}".format(acc))

    print("Optimization Finished!")

    # Calculate accuracy for MNIST test images
    logit,f_accuracy,f_weights,f_biases = sess.run([logits,accuracy,weights,biases], feed_dict={X: X_test,Y: y_test.reshape(-1,1)})
    print("Testing Accuracy:", f_accuracy)

Step 1, Minibatch Loss= 0.5728, Training Accuracy= 0.811
Step 1000, Minibatch Loss= 0.4616, Training Accuracy= 0.802
Step 2000, Minibatch Loss= 0.3815, Training Accuracy= 0.789
Step 3000, Minibatch Loss= 0.2857, Training Accuracy= 0.814
Step 4000, Minibatch Loss= 0.2421, Training Accuracy= 0.906
Step 5000, Minibatch Loss= 0.2017, Training Accuracy= 0.930
Step 6000, Minibatch Loss= 0.1740, Training Accuracy= 0.938
Step 7000, Minibatch Loss= 0.1555, Training Accuracy= 0.947
Step 8000, Minibatch Loss= 0.1266, Training Accuracy= 0.961
Step 9000, Minibatch Loss= 0.1318, Training Accuracy= 0.951
Step 10000, Minibatch Loss= 0.1297, Training Accuracy= 0.950
Optimization Finished!
Testing Accuracy: 0.95866317


In [92]:
logit = np.squeeze(logit)
y_test[logit>0.5] = 1
y_test[logit<=0.5] = 0

In [109]:
for i in range(X_test.shape[0]):
    if(y_test[i]==1):
        print(X_test[i])

[0.38823529 0.59215686 0.87058824]
[0.56862745 0.70980392 0.96078431]
[0.23529412 0.4745098  0.7254902 ]
[0.43921569 0.59607843 0.82352941]
[0.54117647 0.65490196 0.87843137]
[0.65490196 0.70980392 0.89803922]
[0.18431373 0.33333333 0.54509804]
[0.46666667 0.61568627 0.82745098]
[0.40392157 0.58039216 0.87058824]
[0.48235294 0.60392157 0.8745098 ]
[0.21568627 0.4        0.61176471]
[0.68235294 0.75294118 0.96078431]
[0.40784314 0.54509804 0.79607843]
[0.51372549 0.62352941 0.83529412]
[0.52156863 0.63137255 0.88235294]
[0.69019608 0.76078431 0.96862745]
[0.44313725 0.65098039 0.91372549]
[0.2        0.38431373 0.59607843]
[0.59215686 0.75686275 0.98823529]
[0.61960784 0.69803922 0.91372549]
[0.53333333 0.69803922 0.95294118]
[0.48235294 0.62352941 0.8745098 ]
[0.40392157 0.56470588 0.81176471]
[0.63529412 0.76862745 1.        ]
[0.32941176 0.36078431 0.51764706]
[0.79215686 0.83137255 0.98823529]
[0.58431373 0.57254902 0.79215686]
[0. 1. 1.]
[0.25882353 0.45882353 0.70588235]
[0.588235

[0.60392157 0.74509804 0.99607843]
[0.25490196 0.51764706 0.78823529]
[0.37254902 0.56862745 0.86666667]
[0.57254902 0.61960784 0.87058824]
[0.24705882 0.49803922 0.75294118]
[0.4745098  0.6        0.83137255]
[0.43137255 0.6        0.84705882]
[0. 1. 1.]
[0.49019608 0.50196078 0.71764706]
[0.6        0.70588235 0.90196078]
[0.44313725 0.59607843 0.83921569]
[0.72941176 0.79215686 0.96078431]
[0.3372549  0.50980392 0.76078431]
[0.43137255 0.47058824 0.89411765]
[0.64313725 0.77647059 0.91764706]
[0.25490196 0.49019608 0.76470588]
[0.35294118 0.26666667 0.96862745]
[0.61960784 0.75686275 1.        ]
[0.64705882 0.69803922 0.90196078]
[0.47843137 0.45098039 0.62745098]
[0.37647059 0.50196078 0.76078431]
[0.21568627 0.39607843 0.58431373]
[0.59607843 0.74901961 0.99215686]
[0.18823529 0.41176471 0.61568627]
[0.45098039 0.58823529 0.83921569]
[0.67058824 0.76470588 0.94509804]
[0.50588235 0.65098039 0.87058824]
[0.56470588 0.73333333 0.99607843]
[0.24313725 0.33333333 0.52156863]
[0.447058

[0.56078431 0.71764706 0.97254902]
[0.59607843 0.66666667 0.90588235]
[0.65490196 0.7372549  0.94117647]
[0.48627451 0.61960784 0.85490196]
[0.38823529 0.50196078 0.74117647]
[0.78431373 0.81568627 1.        ]
[0.52156863 0.63921569 0.85490196]
[0.38039216 0.36078431 0.6       ]
[0.47058824 0.59607843 0.85098039]
[0.60392157 0.65098039 0.90196078]
[0.4745098  0.61568627 0.86666667]
[0.32156863 0.4745098  0.74509804]
[0.43921569 0.59607843 0.82352941]
[0.2627451  0.49803922 0.73333333]
[0.54509804 0.65098039 0.90196078]
[0.61568627 0.75294118 0.90980392]
[0.6627451  0.72156863 0.91372549]
[0.80784314 0.85098039 1.        ]
[0.65490196 0.70980392 0.91372549]
[0.2        0.3372549  0.53333333]
[0.39215686 0.53333333 0.74509804]
[0.47058824 0.62745098 0.83137255]
[0.34509804 0.54901961 0.84705882]
[0.43137255 0.5372549  0.75686275]
[0.5372549  0.69803922 0.89019608]
[0.12156863 0.71764706 0.81176471]
[0.58039216 0.69411765 0.87058824]
[0.2        0.36470588 0.54901961]
[0.52156863 0.639215

[0.46666667 0.61176471 0.83137255]
[0.19215686 0.29019608 0.54117647]
[0.17254902 0.36470588 0.55294118]
[0.68235294 0.73333333 0.9372549 ]
[0.45882353 0.58823529 0.85882353]
[0.38431373 0.35686275 0.59607843]
[0.29803922 0.42352941 0.68235294]
[0.48235294 0.62745098 0.8627451 ]
[0.21568627 0.44313725 0.69803922]
[0.36078431 0.53333333 0.85882353]
[0.68235294 0.7372549  0.92941176]
[0.35686275 0.38431373 0.57647059]
[0.61176471 0.66666667 0.85882353]
[0.4627451  0.61176471 0.8627451 ]
[0.2627451  0.50196078 0.75294118]
[0.43137255 0.6        0.82352941]
[0.60784314 0.71372549 0.93333333]
[0.47843137 0.61960784 0.83137255]
[0.54901961 0.69019608 0.87843137]
[0.12941176 0.46666667 0.34901961]
[0.40392157 0.55294118 0.78039216]
[0.24705882 0.36078431 0.51372549]
[0.61568627 0.76078431 1.        ]
[0.48627451 0.62352941 0.8745098 ]
[0.59215686 0.72156863 0.8745098 ]
[0.21176471 0.38039216 0.57254902]
[0.4        0.52156863 0.72156863]
[0.46666667 0.63529412 0.83529412]
[0.40392157 0.549019

[0.2627451  0.45098039 0.67843137]
[0.05490196 0.75686275 0.99607843]
[0.54901961 0.65098039 0.90980392]
[0.40784314 0.58823529 0.86666667]
[0.58823529 0.73333333 1.        ]
[0.25490196 0.50588235 0.75686275]
[0.58823529 0.63137255 0.89803922]
[0.45882353 0.61568627 0.84705882]
[0.58823529 0.7372549  0.98823529]
[0.22352941 0.43921569 1.        ]
[0.5372549  0.67843137 0.85882353]
[0.61960784 0.75686275 1.        ]
[0.66666667 0.72941176 0.90980392]
[0.45882353 0.57254902 0.8627451 ]
[0.31372549 0.36078431 0.51764706]
[0.59215686 0.74117647 0.99215686]
[0.24705882 0.47843137 0.74901961]
[0.37254902 0.56470588 0.85490196]
[0.39215686 0.59215686 0.86666667]
[0.2        0.38431373 0.58431373]
[0.16862745 0.35686275 0.58431373]
[0.44705882 0.84705882 0.82745098]
[0.38431373 0.50588235 0.74509804]
[0.67843137 0.7372549  0.91764706]
[0.36862745 0.53333333 0.85882353]
[0.36078431 0.38431373 0.59215686]
[0.19215686 0.41960784 0.65098039]
[0.54509804 0.68235294 0.87843137]
[0.31372549 0.698039

[0.19607843 0.35686275 0.53333333]
[0.23921569 0.3372549  0.47058824]
[0.43529412 0.57254902 0.79215686]
[0.43529412 0.58823529 0.83137255]
[0.54117647 0.5372549  0.75686275]
[0.61568627 0.73333333 0.95686275]
[0.20392157 0.40784314 0.61568627]
[0.23137255 0.43137255 0.67843137]
[0.61568627 0.76078431 0.99607843]
[0.49411765 0.65098039 0.85490196]
[0.50588235 0.65882353 0.8627451 ]
[0.50588235 0.51372549 0.7254902 ]
[0.43921569 0.6        0.84705882]
[0.2        0.35686275 0.54509804]
[0.39215686 0.54117647 0.76862745]
[0.42745098 0.56470588 0.85098039]
[0.6745098  0.72941176 0.9372549 ]
[0.59215686 0.73333333 1.        ]
[0.54509804 0.70196078 0.95686275]
[0.57254902 0.74509804 0.95686275]
[0.45882353 0.58039216 0.79607843]
[0.59215686 0.74117647 0.99215686]
[0.35294118 0.26666667 0.96862745]
[0.57647059 0.74509804 0.99215686]
[0.29019608 0.60392157 0.48235294]
[0.47058824 0.62745098 0.83137255]
[0.70196078 0.76470588 0.93333333]
[0.59607843 0.66666667 0.85098039]
[0.2        0.360784

[0.25490196 0.47843137 0.74901961]
[0.18039216 0.32941176 0.54117647]
[0.50196078 0.51764706 0.7254902 ]
[0.58823529 0.71764706 0.89411765]
[0.43529412 0.6        0.80784314]
[0.64313725 0.70588235 0.9372549 ]
[0.60392157 0.75294118 0.91764706]
[0.39215686 0.58431373 0.85882353]
[0.80392157 0.84313725 1.        ]
[0.23137255 0.39607843 0.60392157]
[0.44313725 0.59215686 0.81960784]
[0.4        0.46666667 0.61960784]
[0.45490196 0.60392157 0.83137255]
[0.43921569 0.58823529 0.81568627]
[0.58039216 0.72941176 0.98039216]
[0.50196078 0.65490196 0.85882353]
[0.21568627 0.51764706 0.80392157]
[0.22745098 0.4        0.61176471]
[0.56862745 0.73333333 0.98823529]
[0.28627451 0.34901961 0.49411765]
[0.66666667 0.72156863 0.9254902 ]
[0.49019608 0.50196078 0.71764706]
[0.4745098  0.62745098 0.87058824]
[0.68235294 0.74901961 0.94117647]
[0.22352941 0.32941176 0.85490196]
[0.36078431 0.34509804 0.57647059]
[0.78823529 0.82352941 0.99215686]
[0.45098039 0.58823529 0.8745098 ]
[0.60784314 0.725490

[0.37647059 0.55686275 0.85882353]
[0.4        0.47843137 0.73333333]
[0.80392157 0.84313725 1.        ]
[0.47058824 0.61568627 0.85882353]
[0.56470588 0.55294118 0.76862745]
[0.39607843 0.42352941 0.63921569]
[0.62745098 0.69411765 0.91372549]
[0.62745098 0.69411765 0.8627451 ]
[0.44705882 0.47058824 0.67843137]
[0.44313725 0.60392157 0.84705882]
[0.40392157 0.59607843 0.87058824]
[0.18039216 0.43137255 1.        ]
[0.43137255 0.6        0.82352941]
[0.48235294 0.49411765 0.70980392]
[0.49803922 0.64705882 0.85882353]
[0.28627451 0.41176471 0.60392157]
[0.2        0.38431373 0.59607843]
[0.38431373 0.61568627 0.89019608]
[0.54509804 0.54509804 0.75686275]
[0.17647059 0.38823529 0.62352941]
[0.43137255 0.56862745 0.78823529]
[0.23137255 0.29803922 0.54509804]
[0. 1. 1.]
[0.39215686 0.59215686 0.87843137]
[0.78039216 0.82352941 1.        ]
[0.44705882 0.58431373 0.83529412]
[0.21176471 0.41568627 0.65098039]
[0.14117647 0.3254902  0.56862745]
[0.22745098 0.45882353 0.70196078]
[0.388235

[0.38431373 0.57254902 0.85490196]
[0.32156863 0.43137255 0.56862745]
[0.38431373 0.60392157 0.88235294]
[0.58823529 0.67058824 0.90980392]
[0.61960784 0.68235294 0.86666667]
[0.65490196 0.68235294 0.92941176]
[0.37254902 0.54509804 0.84705882]
[0.81960784 0.85098039 1.        ]
[0.54117647 0.68627451 0.92156863]
[0.49803922 0.50980392 0.7254902 ]
[0.59215686 0.74117647 0.99215686]
[0.48235294 0.64313725 0.89019608]
[0.16470588 0.34901961 0.55294118]
[0.54509804 0.64705882 0.90588235]
[0.2        0.40392157 0.63921569]
[0.76470588 0.81176471 1.        ]
[0.56862745 0.7254902  0.98039216]
[0.60784314 0.67843137 0.91764706]
[0.49411765 0.65098039 0.85882353]
[0.20784314 0.36470588 0.55686275]
[0.2        0.84705882 0.90588235]
[0.18039216 0.42745098 0.6       ]
[0.57647059 0.7372549  0.98039216]
[0.6627451  0.71764706 0.9254902 ]
[0.56470588 0.58823529 0.81960784]
[0.15686275 0.39607843 1.        ]
[0.39607843 0.61176471 0.89803922]
[0.47058824 0.57254902 0.63921569]
[0.4627451  0.592156

[0.19607843 0.28235294 0.50980392]
[0.59607843 0.75686275 1.        ]
[0.24313725 0.41960784 0.61960784]
[0.51372549 0.62745098 0.89019608]
[0.         0.52941176 0.40392157]
[0.48235294 0.48627451 0.70588235]
[0.41176471 0.55294118 0.82745098]
[0.21568627 0.5254902  0.44313725]
[0.4745098  0.56862745 0.63921569]
[0.47843137 0.62745098 0.87843137]
[0.51372549 0.65490196 0.89019608]
[0.40784314 0.42352941 0.65098039]
[0.22352941 0.41176471 0.6627451 ]
[0.50196078 0.64705882 0.85098039]
[0.4        0.80392157 0.78431373]
[0.30588235 0.37254902 0.57254902]
[0.77647059 0.81960784 0.99215686]
[0.21960784 0.40392157 0.61568627]
[0.63529412 0.71372549 0.92941176]
[0.         0.41960784 0.97647059]
[0.58431373 0.72941176 0.97254902]
[0.47058824 0.62745098 0.88235294]
[0.25490196 0.41176471 0.61960784]
[0.39607843 0.56078431 0.79215686]
[0.43529412 0.59607843 0.84313725]
[0.23921569 0.41568627 0.67843137]
[0.35686275 0.27058824 0.97254902]
[0.21176471 0.36862745 0.57254902]
[0.31372549 0.352941

[0.20392157 0.44705882 1.        ]
[0.45490196 0.56078431 0.66666667]
[0.42745098 0.64705882 0.87843137]
[0.21568627 0.41176471 0.61960784]
[0.4745098  0.62352941 0.8745098 ]
[0.34117647 0.42352941 0.57254902]
[0.24705882 0.4745098  0.70588235]
[0.40392157 0.59215686 0.8745098 ]
[0.40392157 0.58431373 0.8627451 ]
[0.43137255 0.6        0.82352941]
[0.65882353 0.71372549 0.91764706]
[0.62745098 0.70588235 0.89411765]
[0.22745098 0.4745098  0.74117647]
[0.40392157 0.42745098 0.63529412]
[0.38823529 0.57647059 0.85882353]
[0.5372549  0.71372549 0.97647059]
[0.2       0.4745098 0.7372549]
[0.48627451 0.62745098 0.8627451 ]
[0.23529412 0.3254902  0.51372549]
[0.50588235 0.63137255 0.89019608]
[0.23529412 0.43921569 0.64705882]
[0.65882353 0.72941176 0.89019608]
[0.34901961 0.25490196 0.95294118]
[0.58823529 0.7372549  0.98823529]
[0. 1. 1.]
[0.42352941 0.6        0.82352941]
[0.61960784 0.76470588 1.        ]
[0.53333333 0.69019608 0.87843137]
[0.56078431 0.6627451  0.9254902 ]
[0.57254902 

[0.60784314 0.65490196 0.90588235]
[0.47058824 0.56470588 0.82352941]
[0.56078431 0.6745098  0.89803922]
[0.39215686 0.58039216 0.8627451 ]
[0.45882353 0.63137255 0.88235294]
[0.21176471 0.47843137 0.74117647]
[0.61176471 0.68627451 0.85490196]
[0.51372549 0.51764706 0.7372549 ]
[0.49019608 0.62352941 0.88235294]
[0.30980392 0.70196078 0.91764706]
[0.43529412 0.58431373 0.81176471]
[0.32941176 0.55686275 0.81176471]
[0.39607843 0.57647059 0.87843137]
[0.45098039 0.56470588 0.85490196]
[0.6        0.74901961 1.        ]
[0.42745098 0.56078431 0.79607843]
[0.38823529 0.55294118 0.81568627]
[0.51372549 0.63137255 0.90980392]
[0.58039216 0.74509804 1.        ]
[0.49019608 0.50588235 0.73333333]
[0.65882353 0.71372549 0.92156863]
[0.6        0.7372549  0.87058824]
[0.76862745 0.81960784 1.        ]
[0.61568627 0.68627451 0.91764706]
[0.36470588 0.50980392 0.77647059]
[0.46666667 0.60392157 0.85098039]
[0.79215686 0.82745098 0.99607843]
[0.58431373 0.73333333 0.98431373]
[0.61960784 0.686274

[0.44313725 0.55686275 0.85098039]
[0.00784314 0.5372549  0.41176471]
[0.58431373 0.75686275 0.99607843]
[0.65098039 0.71372549 0.88235294]
[0.38431373 0.35686275 0.59607843]
[0.49019608 0.66666667 0.86666667]
[0.49019608 0.61568627 0.87058824]
[0.4        0.54509804 0.77254902]
[0.45882353 0.59607843 0.84705882]
[0.53333333 0.69803922 0.95294118]
[0.5372549  0.64313725 0.89411765]
[0.58431373 0.73333333 0.98431373]
[0.2745098  0.49803922 0.76862745]
[0.18039216 0.4        0.61568627]
[0.22352941 0.34509804 0.55294118]
[0.56862745 0.72941176 0.97647059]
[0.44705882 0.46666667 0.68235294]
[0.36470588 0.58039216 0.8745098 ]
[0.22352941 0.4627451  0.72941176]
[0.         0.5372549  0.41568627]
[0.24313725 0.43529412 0.61568627]
[0.41176471 0.60392157 0.87058824]
[0.61960784 0.70196078 0.94509804]
[0.4745098  0.61568627 0.85098039]
[0.4745098  0.60392157 0.8745098 ]
[0.51372549 0.66666667 0.87058824]
[0.41960784 0.81568627 0.75686275]
[0.17254902 0.37254902 0.61960784]
[0.54901961 0.654901

[0.54117647 0.52941176 0.96078431]
[0.65490196 0.70980392 0.91372549]
[0.69019608 0.75294118 0.93333333]
[0.40392157 0.54901961 0.81568627]
[0.77254902 0.81568627 0.98823529]
[0.65882353 0.72156863 0.90196078]
[0.65098039 0.71372549 0.89411765]
[0.6        0.74901961 1.        ]
[0.39215686 0.50980392 0.76470588]
[0.25098039 0.51764706 0.78039216]
[0.24313725 0.48235294 0.74117647]
[0.51764706 0.66666667 0.87843137]
[0.6745098  0.74117647 0.90980392]
[0.23921569 0.45098039 0.68627451]
[0.57647059 0.73333333 0.98823529]
[0.14509804 0.34901961 0.55686275]
[0.23529412 0.42352941 0.6745098 ]
[0.63529412 0.67058824 0.89411765]
[0.53333333 0.67058824 0.86666667]
[0.54901961 0.70980392 0.99607843]
[0.18431373 0.29019608 0.51372549]
[0.6627451  0.71372549 0.93333333]
[0.10196078 0.8        0.96078431]
[0.68235294 0.74509804 0.9254902 ]
[0.50980392 0.60784314 0.80392157]
[0.36078431 0.50980392 0.76470588]
[0.37647059 0.56078431 0.77254902]
[0.16470588 0.35686275 0.55294118]
[0.54901961 0.701960

In [95]:
import math

def sigmoid(x):
    if(x>50):
        return 1
    if(x<-50):
        return 1e-12
    return 1 / (1 + math.exp(-x))

In [96]:
import numpy as np
h1 = np.array(f_weights['h1'])
#h2 = np.array(f_weights['h2'])
out_w = np.array(f_weights['out'])
b1 = np.array(f_biases['b1'])
#b2 = np.array(f_biases['b2'])
out_b = np.array(f_biases['out'])

In [97]:
h1

array([[ 0.06192115,  7.0181336 ],
       [-7.8160367 ,  3.1022456 ],
       [-0.06261314, -8.99723   ]], dtype=float32)

In [115]:
from scipy.optimize import minimize
def objective(x,w):
    w = np.array(w)
    b = w[-1]
    w = w[:-1]
    #k = sigmoid(np.sum(x*w) + b)
    k = np.sum(x*w) + b
    return np.sum(k)
def objective_max(x,w):
    w = np.array(w)
    b = w[-1]
    w = w[:-1]
    #k = sigmoid(np.sum(x*w) + b)
    k = np.sum(x*w) + b
    return -np.sum(k)

In [116]:
# forward phase for via
from scipy import optimize
def forward(input_interval,h1_interval,out_interval):
    for i in range(h1.shape[1]):
        w = h1[:,i]
        #w = np.hstack((h1[:,i],b1[i]))
        
        #w = tuple(np.hstack((w,b1[i])))
        bnds = []
        for j in range(input_interval.shape[1]):
            bnds.append((input_interval[0,j],input_interval[1,j]))
        #x0 = (0,0)
        
        bnds = np.array(bnds)
        x0 = np.zeros(input_interval.shape[1])
        for j in range(x0.shape[0]):
            x0[j] = bnds[0,i]
        bnds = tuple(bnds)
        
        sol = optimize.linprog(c = w,bounds=bnds,method='simplex',options=dict(tol=1e-15))
        print("minimum")
        print(sol['fun'])
        print(b1[i])
        print(sigmoid(sol['fun']+b1[i]))
        h1_interval[0,i] = sigmoid(sol['fun'] + b1[i])
        sol = optimize.linprog(c = -w,bounds=bnds,method='simplex')
        #sol = minimize(objective_max,x0,(w,),bounds = bnds)
        h1_interval[1,i] = sigmoid(-(sol['fun'])+b1[i])
        print("h1 change in forward")
        print(h1_interval)
        
        
    # out layer
    for i in range(out_w.shape[1]):
        w = out_w[:,i]
        #w = np.hstack((h1[:,i],b1[i]))
        #w = tuple(np.hstack((w,out_b[i])))
        bnds = []
        for j in range(h1_interval.shape[1]):
            bnds.append((h1_interval[0,j],h1_interval[1,j]))
        x0 = np.zeros((h1_interval.shape[1]))
        bnds = np.array(bnds)
        bnds = tuple(bnds)
        #sol = minimize (objective,x0,(w,),bounds = bnds)
        sol = optimize.linprog(c = w,bounds=bnds,method='simplex')
        out_interval[0,i] = sigmoid(sol['fun'] + out_b[i])
        #sol = minimize(objective_max,x0,(w,),bounds = bnds)
        sol = optimize.linprog(c = -w,bounds=bnds,method='simplex')
        out_interval[1,i] = sigmoid(-(sol['fun'])+out_b[i])
        print("outchange in forward")
        print(out_interval)
    

In [117]:
def invsig(interval):
    ans = -np.log(1/(interval) - 1 )
    ans[ans<-30] = -30
    return ans

In [118]:
def bound(weights,interval,bias,mode,layer):
    A_ub = weights.T
    ones = np.identity((weights.T).shape[0])
    zeros = np.zeros(((weights.T).shape[0],(weights.T).shape[0]))
    #A_ub = np.hstack((A_ub,ones,zeros))
    # make intervals ready for log
    for i in range(interval.shape[1]):
        if(interval[1,i]>=1):
            interval[1,i]= 1-1e-6
        if(interval[0,i]==0):
            interval[0,i] = 1e-6
            
    b_ub = invsig(interval[1,:]) - bias
    b_ub1 = invsig(interval[0,:]) - bias
    print(b_ub)
    print(b_ub1)
    #A_ub1 = np.hstack((weights.T,zeros,ones))
    A_ub = np.vstack((A_ub,-A_ub))
    b_ub = np.hstack((b_ub,-b_ub1))
    new_interval = np.zeros((A_ub.shape[1]))
    bnds = []
    #print("solving")
    #print(A_ub)
    #print(b_ub)
    if(layer=="hidden"):
        for j in range(A_ub.shape[1]):
            bnds.append((0,1))
    else:
        for j in range(A_ub.shape[1]):
            bnds.append((0,1))
    bnds = tuple(bnds)
    for i in range(A_ub.shape[1]):
        c = np.zeros((A_ub.shape[1]))
        if(mode=="min"):
            c[i] = 1
        else:
            c[i] = -1
        res = scipy.optimize.linprog(c,A_ub = A_ub,b_ub = b_ub,options=dict(tol=1e-15),bounds = bnds)
        #print(res)
        
        new_interval[i] = res['x'][i]
        
    return new_interval

In [119]:
import scipy
def backward(input_interval,h1_interval,out_interval):
    #print("computing for hidden layer")
    max_bounds = bound(out_w,out_interval,out_b,"max","hidden")
    h1_interval[1,:] = max_bounds
    min_bounds = bound(out_w,out_interval,out_b,"min","hidden")
    h1_interval[0,:] = min_bounds
    #print("hidden chagne in backward")
    #print(h1_interval)
    #max_bounds = bound(h2,h2_interval,b2,"max")
    #min_bounds = bound(h2,h2_interval,b2,"min")
    #print("computing for input interval")
    max_bounds = bound(h1,h1_interval,b1,"max","input")
    input_interval[1,:] = max_bounds
    min_bounds = bound(h1,h1_interval,b1,"min","input")
    input_interval[0,:] = min_bounds
    #print(" input interval cahnge in backward")
    #print(input_interval)

In [130]:
def test_consistency(input_interval):
    # initialize hidden layer/s and output intervals
    h1_interval = np.zeros((2,n_hidden_1))
    h1_interval[1,:] = h1_interval[1,:] + 1
    out_interval = np.zeros((2,num_classes))
    out_interval[1,:] = out_interval[1,:] + 1
    abs_diff = 100
    initial_val = np.sum(h1_interval) + np.sum(input_interval) + np.sum(out_interval)
    while(abs_diff>1 ):
        #print("abs diff")
        #print(abs_diff)
        print("input before fwd")
        print("input")
        print(input_interval)
        print(h1_interval)
        print(out_interval)
        forward(input_interval,h1_interval,out_interval)
        print("after fwd")
        print(input_interval)
        print(h1_interval)
        print(out_interval)
        # check for consistency
        if(out_interval[0,0]<0.5):
            print("consistency detected")
            return 1
        print("before bkw")
        print(input_interval)
        print(h1_interval)
        print(out_interval)
        backward(input_interval,h1_interval,out_interval)
        print("after bkw")
        print(input_interval)
        print(h1_interval)
        print(out_interval)
        final_val = np.sum(h1_interval) + np.sum(input_interval) + np.sum(out_interval)
        abs_diff = abs(initial_val - final_val)
        initial_val = final_val
    return 0
        

In [131]:
import copy
# rule extraction using via (and gate)
data_X = X_test
data_y = y_test
input_max = 1
input_min = 0
input_interval = np.zeros((2,num_input))
"""
input_interval[1,0] = 1
input_interval[1,1] = 0.4

h1_interval = np.zeros((2,n_hidden_1))
h1_interval[1,:] = h1_interval[1,:] + 1

# set out interval according to rule to test (rules will be proved via contradiction using inconsistencies in VIA analysis)
out_interval = np.zeros((2,num_classes))
out_interval[1,:] = out_interval[1,:] + 1
"""
#rules = np.zeros((data_X.shape[0],2,num_input))
t = 0
tol = 0.1
#for i in range(data_X.shape[0]):
for i in range(400):
    
    if(data_y[i]==1):
        #print("this time ")
        #print(data_X[i])
        flag = 0
        """
        for j in range(rules.shape[0]):
            if(np.sum(rules[j])==0):
                continue
            if(flag ==1):
                break
            for k in range(data_X.shape[1]):
                if(rules[j,0,k]<data_X[i,k] and rules[j,1,k]>data_X[i,k]):
                    flag = 1
                    break
        """
        if(flag==1):
            continue
        else:
        

            for j in range(input_interval.shape[1]):
                input_interval[0,j] = data_X[i,j]
                input_interval[1,j] = data_X[i,j]
            print("testing this data point")
            print(input_interval)
            
            for k in range(input_interval.shape[1]):
                # try decreasing the lower bound
                test_val = 0
                while(test_val==0):
                    print("try decreasing")
                    print("input interval")
                    print(input_interval)
                    test_interval = np.copy(input_interval)
                    test_interval[0,k] = test_interval[0,k] - tol
                    input_interval = np.copy(test_interval)
                    if(test_interval[0,k]<tol):
                        break
                    test_val = test_consistency(input_interval)
                    if(test_val== 0):
                        input_interval = np.copy(test_interval)
                    else:
                        input_interval[0,k] = input_interval[0,k] + tol
                
                #now try increasing the upper bound
                test_val = 0
                while(test_val==0):
                    print("try increasing")
                    print("input interval")
                    print(input_interval)
                    test_interval = np.copy(input_interval)
                    test_interval[1,k] = test_interval[1,k] + tol
                    input_interval = np.copy(test_interval)
                    if(test_interval[1,k]>1-tol):
                        break
                    test_val = test_consistency(input_interval)
                    if(test_val==0):
                        input_interval = np.copy(test_interval)
                    else:
                        input_interval[1,k] = input_interval[1,k] - tol
            print("rule generate")
            print(input_interval)
            #rules[t] = input_interval
            #t = t+1
            #print(rules)
            



testing this data point
[[0.38823529 0.59215686 0.87058824]
 [0.38823529 0.59215686 0.87058824]]
try decreasing
input interval
[[0.38823529 0.59215686 0.87058824]
 [0.38823529 0.59215686 0.87058824]]
input before fwd
input
[[0.28823529 0.59215686 0.87058824]
 [0.38823529 0.59215686 0.87058824]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.664982178339771
1.6656325
0.04745526056900954
h1 change in forward
[[0.04745526 0.        ]
 [0.04773595 1.        ]]
minimum
-3.972992401497037
-0.64594835
0.009766904837475894
h1 change in forward
[[0.04745526 0.0097669 ]
 [0.04773595 0.01950996]]
outchange in forward
[[0.9002619 ]
 [0.90806224]]
after fwd
[[0.28823529 0.59215686 0.87058824]
 [0.38823529 0.59215686 0.87058824]]
[[0.04745526 0.0097669 ]
 [0.04773595 0.01950996]]
[[0.9002619 ]
 [0.90806224]]
before bkw
[[0.28823529 0.59215686 0.87058824]
 [0.38823529 0.59215686 0.87058824]]
[[0.04745526 0.0097669 ]
 [0.04773595 0.01950996]]
[[0.9002619 ]
 [0.90806224]]
[-0.3753282]
[-0.46539125]
[-0.375

[-3.30000931 -1.457647  ]
[-15.48114204 -13.16956121]
[-3.30000931 -1.457647  ]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.4141992  0.30674145]
 [0.88810052 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.63231663e-01 1.08747863e-01]]
[[0.84280043]
 [0.87649242]]
try increasing
input interval
[[0.03529412 0.4745098  0.7254902 ]
 [0.33529412 0.4745098  0.7254902 ]]
input before fwd
input
[[0.03529412 0.4745098  0.7254902 ]
 [0.43529412 0.4745098  0.7254902 ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.752025812688996
1.6656325
0.11042636903328874
h1 change in forward
[[0.11042637 0.        ]
 [0.11288301 1.        ]]
minimum
-4.8076570782006955
-0.64594835
0.004262595063000024
h1 change in forward
[[0.11042637 0.0042626 ]
 [0.11288301 0.06621421]]
outchange in forward
[[0.79945573]
 [0.87649242]]
after fwd
[[0.03529412 0.4745098  0.7254902 ]
 [0.43529412 0.4745098  0.7254902 ]]
[[0.11042637 0.0042626 ]
 [0.11288301 0.06621421]]
[[0.79945573]
 [0.87649242]]
before 

[-2.98737845 -1.16720454]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.37420056 0.2607955 ]
 [0.94695968 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.10527957e-01 1.40257502e-01]]
[[0.80113922]
 [0.87391557]]
input before fwd
input
[[0.         0.37420056 0.2607955 ]
 [0.94695968 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.10527957e-01 1.40257502e-01]]
[[0.80113922]
 [0.87391557]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [2.28495636e-01 1.40257502e-01]]
minimum
-7.8363675480489565
-0.64594835
0.00020705564682915964
h1 change in forward
[[1.99917929e-03 2.07055647e-04]
 [2.28495636e-01 9.98837187e-01]]
outchange in forward
[[4.20210123e-04]
 [9.34107778e-01]]
after fwd
[[0.         0.37420056 0.2607955 ]
 [0.94695968 1.         1.        ]]
[[1.99917929e-03 2.07055647e-04]
 [2.28495636e-01 9.98837187e-01]]
[[4.20210123e-04]
 [9.34107778e-01]]
consistency detected
try increas

[-1.96411943 -0.27993579]
[-15.48114204 -13.16956121]
[-1.96411943 -0.27993579]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.24328267 0.11743521]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.25927405e-01 2.83760480e-01]]
[[0.52295749]
 [0.8460075 ]]
try increasing
input interval
[[0.08431373 0.33333333 0.54509804]
 [0.28431373 0.43333333 0.64509804]]
input before fwd
input
[[0.08431373 0.33333333 0.54509804]
 [0.28431373 0.43333333 0.74509804]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.42838136559608
1.6656325
0.1464463962551535
h1 change in forward
[[0.1464464  0.        ]
 [0.27763197 1.        ]]
minimum
-5.078011265922994
-0.64594835
0.003256113273467755
h1 change in forward
[[0.1464464  0.00325611]
 [0.27763197 0.09879708]]
outchange in forward
[[0.52295749]
 [0.85209221]]
after fwd
[[0.08431373 0.33333333 0.54509804]
 [0.28431373 0.43333333 0.74509804]]
[[0.1464464  0.00325611]
 [0.27763197 0.09879708]]
[[0.52295749]
 [0.85209221]]
before bkw

minimum
-4.59063383808323
1.6656325
0.050931404913318414
h1 change in forward
[[0.0509314  0.        ]
 [0.10909168 1.        ]]
minimum
-6.315065686375487
-0.64594835
0.0009472365357068687
h1 change in forward
[[0.0509314  0.00094724]
 [0.10909168 0.14955495]]
outchange in forward
[[0.65699377]
 [0.91286973]]
after fwd
[[0.00392157 0.48039216 0.87058824]
 [0.70392157 0.58039216 0.87058824]]
[[0.0509314  0.00094724]
 [0.10909168 0.14955495]]
[[0.65699377]
 [0.91286973]]
before bkw
[[0.00392157 0.48039216 0.87058824]
 [0.70392157 0.58039216 0.87058824]]
[[0.0509314  0.00094724]
 [0.10909168 0.14955495]]
[[0.65699377]
 [0.91286973]]
[-0.31634042]
[-2.01560334]
[-0.31634042]
[-2.01560334]
[-2.35769146 -0.60674773]
[-15.48114204 -13.16956121]
[-2.35769146 -0.60674773]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.2936371  0.17097316]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.33575201e-01 2.22233784e-01]]
[[0.65699377]
 [0.91286973]]
try decreasing
inp

minimum
-4.726955220512316
1.6656325
0.04473114820912509
h1 change in forward
[[0.04473115 0.        ]
 [0.18643443 1.        ]]
minimum
-4.153200906865737
-0.64594835
0.008169461600837485
h1 change in forward
[[0.04473115 0.00816946]
 [0.18643443 0.20238621]]
outchange in forward
[[0.42639426]
 [0.91061357]]
after fwd
[[0.01568627 0.4        0.61176471]
 [0.41568627 0.6        0.61176471]]
[[0.04473115 0.00816946]
 [0.18643443 0.20238621]]
[[0.42639426]
 [0.91061357]]
consistency detected
try decreasing
input interval
[[0.01568627 0.4        0.61176471]
 [0.41568627 0.5        0.61176471]]
input before fwd
input
[[0.01568627 0.4        0.51176471]
 [0.41568627 0.5        0.61176471]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.9453515503920764
1.6656325
0.09281660569135289
h1 change in forward
[[0.09281661 0.        ]
 [0.18738599 1.        ]]
minimum
-4.153200906865737
-0.64594835
0.008169461600837485
h1 change in forward
[[0.09281661 0.00816946]
 [0.18738599 0.31390014]]
outchange in

h1 change in forward
[[0.06750534 0.01876283]
 [0.06789617 0.03714323]]
outchange in forward
[[0.87195903]
 [0.88967829]]
after fwd
[[0.30784314 0.54509804 0.79607843]
 [0.40784314 0.54509804 0.79607843]]
[[0.06750534 0.01876283]
 [0.06789617 0.03714323]]
[[0.87195903]
 [0.88967829]]
before bkw
[[0.30784314 0.54509804 0.79607843]
 [0.40784314 0.54509804 0.79607843]]
[[0.06750534 0.01876283]
 [0.06789617 0.03714323]]
[[0.87195903]
 [0.88967829]]
[-0.57807001]
[-0.74713709]
[-0.57807001]
[-0.74713709]
[-3.62395654 -1.76453367]
[-15.48114204 -13.16956121]
[-3.62395654 -1.76453367]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.45564569 0.3550079 ]
 [0.82626866 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.23648537e-01 8.23768743e-02]]
[[0.87195903]
 [0.88967829]]
try decreasing
input interval
[[0.30784314 0.54509804 0.79607843]
 [0.40784314 0.54509804 0.79607843]]
input before fwd
input
[[0.20784314 0.54509804 0.79607843]
 [0.40784314 0.54509804 0.79607843]]
[[0. 0.]


[-3.48236264 -1.62975782]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.43752987 0.33384033]
 [0.85338543 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.39826691e-01 9.31550507e-02]]
[[0.86064253]
 [0.89294479]]
input before fwd
input
[[0.         0.43752987 0.33384033]
 [0.85338543 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.39826691e-01 9.31550507e-02]]
[[0.86064253]
 [0.89294479]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [1.51590940e-01 9.31550507e-02]]
minimum
-7.639904485931881
-0.64594835
0.00025199410534296456
h1 change in forward
[[1.99917929e-03 2.51994105e-04]
 [1.51590940e-01 9.95687141e-01]]
outchange in forward
[[6.87971893e-04]
 [9.34082687e-01]]
after fwd
[[0.         0.43752987 0.33384033]
 [0.85338543 1.         1.        ]]
[[1.99917929e-03 2.51994105e-04]
 [1.51590940e-01 9.95687141e-01]]
[[6.87971893e-04]
 [9.34082687e-01]]
consistency detected
try increasi

 [0.69112124 1.1        1.        ]]
rule generate
[[0.1        0.54491378 0.46050509]
 [0.69112124 1.1        1.1       ]]
testing this data point
[[0.2        0.38431373 0.59607843]
 [0.2        0.38431373 0.59607843]]
try decreasing
input interval
[[0.2        0.38431373 0.59607843]
 [0.2        0.38431373 0.59607843]]
input before fwd
input
[[0.1        0.38431373 0.59607843]
 [0.2        0.38431373 0.59607843]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.034940413224931
1.6656325
0.20273168426789503
h1 change in forward
[[0.20273168 0.        ]
 [0.20373437 1.        ]]
minimum
-3.469005576302023
-0.64594835
0.016064413868907085
h1 change in forward
[[0.20273168 0.01606441]
 [0.20373437 0.0318873 ]]
outchange in forward
[[0.75864587]
 [0.78496495]]
after fwd
[[0.1        0.38431373 0.59607843]
 [0.2        0.38431373 0.59607843]]
[[0.20273168 0.01606441]
 [0.20373437 0.0318873 ]]
[[0.75864587]
 [0.78496495]]
before bkw
[[0.1        0.38431373 0.59607843]
 [0.2        0.38431373 0.5

[-1.91595503 -0.24151789]
[-15.48114204 -13.16956121]
[-1.91595503 -0.24151789]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.23712042 0.11105811]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.37744112e-01 2.91632982e-01]]
[[0.50512307]
 [0.88214168]]
try increasing
input interval
[[0.         0.38431373 0.59607843]
 [0.4        0.48431373 0.69607843]]
input before fwd
input
[[0.         0.38431373 0.59607843]
 [0.4        0.48431373 0.79607843]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.835258827197786
1.6656325
0.10251140603274181
h1 change in forward
[[0.10251141 0.        ]
 [0.20575079 1.        ]]
minimum
-5.970264855553121
-0.64594835
0.0013367007860289443
h1 change in forward
[[0.10251141 0.0013367 ]
 [0.20575079 0.15455811]]
outchange in forward
[[0.50512307]
 [0.88431969]]
after fwd
[[0.         0.38431373 0.59607843]
 [0.4        0.48431373 0.79607843]]
[[0.10251141 0.0013367 ]
 [0.20575079 0.15455811]]
[[0.50512307]
 [0.88431969]]
before 

[-3.38447583 -1.53714971]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.42500602 0.31926939]
 [0.87205156 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.52020208e-01 1.01278590e-01]]
[[0.85156876]
 [0.89350318]]
input before fwd
input
[[0.         0.42500602 0.31926939]
 [0.87205156 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.52020208e-01 1.01278590e-01]]
[[0.85156876]
 [0.89350318]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [1.64898626e-01 1.01278590e-01]]
minimum
-7.678756518898961
-0.64594835
0.00024239370043505813
h1 change in forward
[[1.99917929e-03 2.42393700e-04]
 [1.64898626e-01 9.96678235e-01]]
outchange in forward
[[6.29173565e-04]
 [9.34088048e-01]]
after fwd
[[0.         0.42500602 0.31926939]
 [0.87205156 1.         1.        ]]
[[1.99917929e-03 2.42393700e-04]
 [1.64898626e-01 9.96678235e-01]]
[[6.29173565e-04]
 [9.34088048e-01]]
consistency detected
try increasi

h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [1.04823904e-01 6.46544196e-02]]
minimum
-7.47568568118513
-0.64594835
0.000296954677922874
h1 change in forward
[[1.99917929e-03 2.96954678e-04]
 [1.04823904e-01 9.86933962e-01]]
outchange in forward
[[0.00098774]
 [0.93405757]]
after fwd
[[0.         0.49046533 0.39595152]
 [0.77381774 1.         1.        ]]
[[1.99917929e-03 2.96954678e-04]
 [1.04823904e-01 9.86933962e-01]]
[[0.00098774]
 [0.93405757]]
consistency detected
try increasing
input interval
[[0.1        0.49046533 0.39595152]
 [0.77381774 1.         1.        ]]
input before fwd
input
[[0.1        0.49046533 0.39595152]
 [0.87381774 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770112
1.6656325
0.002011571860831458
h1 change in forward
[[0.00201157 0.        ]
 [0.10540637 1.        ]]
minimum
-6.773872317156199
-0.64594835
0.000598897708606185
h1 change in forward
[[2.01157186e-03 5.98897709e-04]
 [1.05406370e-01 9.93480393e-01]]
outcha

[-2.79178239 -0.98911191]
[-15.48114204 -13.16956121]
[-2.79178239 -0.98911191]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.34917559 0.23245102]
 [0.98327045 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.44872323e-01 1.63138335e-01]]
[[0.76600814]
 [0.90886117]]
try increasing
input interval
[[0.00392157 0.56470588 0.81176471]
 [0.60392157 0.56470588 0.81176471]]
input before fwd
input
[[0.00392157 0.56470588 0.81176471]
 [0.70392157 0.56470588 0.81176471]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.464346214661411
1.6656325
0.05739372318635951
h1 change in forward
[[0.05739372 0.        ]
 [0.05978415 1.        ]]
minimum
-5.52425500645357
-0.64594835
0.0020864484077023145
h1 change in forward
[[0.05739372 0.00208645]
 [0.05978415 0.22140286]]
outchange in forward
[[0.57351842]
 [0.90886117]]
after fwd
[[0.00392157 0.56470588 0.81176471]
 [0.70392157 0.56470588 0.81176471]]
[[0.05739372 0.00208645]
 [0.05978415 0.22140286]]
[[0.57351842]
 [0.90886117]]
before b

minimum
-8.65406140089035
1.6656325
0.0009216444996092924
h1 change in forward
[[9.21644500e-04 0.00000000e+00]
 [1.07104154e-01 1.00000000e+00]]
minimum
-6.780792615658099
-0.64594835
0.0005947699219760457
h1 change in forward
[[9.21644500e-04 5.94769922e-04]
 [1.07104154e-01 9.96248645e-01]]
outchange in forward
[[8.95386798e-04]
 [9.34291849e-01]]
after fwd
[[0.1        0.48823459 0.29331943]
 [0.77718958 1.1        1.        ]]
[[9.21644500e-04 5.94769922e-04]
 [1.07104154e-01 9.96248645e-01]]
[[8.95386798e-04]
 [9.34291849e-01]]
consistency detected
try increasing
input interval
[[0.1        0.48823459 0.39331943]
 [0.77718958 1.1        1.        ]]
rule generate
[[0.1        0.48823459 0.39331943]
 [0.77718958 1.1        1.1       ]]
testing this data point
[[0.32941176 0.36078431 0.51764706]
 [0.32941176 0.36078431 0.51764706]]
try decreasing
input interval
[[0.32941176 0.36078431 0.51764706]
 [0.32941176 0.36078431 0.51764706]]
input before fwd
input
[[0.22941176 0.36078431 0.

 [0.05610184 0.13054075]]
[[0.75815063]
 [0.84557097]]
[-0.96525181]
[-1.52296225]
[-0.96525181]
[-1.52296225]
[-2.75336847 -0.95451547]
[-15.48114204 -13.16956121]
[-2.75336847 -0.95451547]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.34426084 0.22692644]
 [0.99034773 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.52044848e-01 1.67916800e-01]]
[[0.75815063]
 [0.84557097]]
input before fwd
input
[[0.         0.34426084 0.22692644]
 [0.99034773 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.52044848e-01 1.67916800e-01]]
[[0.75815063]
 [0.84557097]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [2.73287230e-01 1.67916800e-01]]
minimum
-7.929247926035135
-0.64594835
0.00018869379517898427
h1 change in forward
[[1.99917929e-03 1.88693795e-04]
 [2.73287230e-01 9.99367363e-01]]
outchange in forward
[[3.19065889e-04]
 [9.34118028e-01]]
after fwd
[[0.         0.34426084 0.22692644]
 [0.99034

after bkw
[[0.         0.34137237 0.22368647]
 [0.99449829 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.56324683e-01 1.70768103e-01]]
[[0.75337728]
 [0.86628104]]
try increasing
input interval
[[0.05882353 0.45882353 0.70588235]
 [0.45882353 0.45882353 0.70588235]]
input before fwd
input
[[0.05882353 0.45882353 0.70588235]
 [0.55882353 0.45882353 0.70588235]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.626736638475867
1.6656325
0.12334760265127107
h1 change in forward
[[0.1233476  0.        ]
 [0.12673469 1.        ]]
minimum
-4.514770931356094
-0.64594835
0.005704839348228984
h1 change in forward
[[0.1233476  0.00570484]
 [0.12673469 0.16088574]]
outchange in forward
[[0.60839055]
 [0.86628104]]
after fwd
[[0.05882353 0.45882353 0.70588235]
 [0.55882353 0.45882353 0.70588235]]
[[0.1233476  0.00570484]
 [0.12673469 0.16088574]]
[[0.60839055]
 [0.86628104]]
before bkw
[[0.05882353 0.45882353 0.70588235]
 [0.55882353 0.45882353 0.70588235]]
[[0.1233476  0.00570484]
 [0.126

outchange in forward
[[0.86220789]
 [0.89733049]]
after fwd
[[0.05686275 0.52156863 0.82352941]
 [0.45686275 0.52156863 0.82352941]]
[[0.07878217 0.00237987]
 [0.08059861 0.03801296]]
[[0.86220789]
 [0.89733049]]
before bkw
[[0.05686275 0.52156863 0.82352941]
 [0.45686275 0.52156863 0.82352941]]
[[0.07878217 0.00237987]
 [0.08059861 0.03801296]]
[[0.86220789]
 [0.89733049]]
[-0.49762021]
[-0.83177893]
[-0.49762021]
[-0.83177893]
[-3.50052504 -1.64699349]
[-15.48114204 -13.16956121]
[-3.50052504 -1.64699349]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.4398536  0.33654973]
 [0.84991455 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.37656461e-01 9.17092045e-02]]
[[0.86220789]
 [0.89733049]]
try increasing
input interval
[[0.05686275 0.52156863 0.82352941]
 [0.45686275 0.52156863 0.82352941]]
input before fwd
input
[[0.05686275 0.52156863 0.82352941]
 [0.55686275 0.52156863 0.82352941]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.124642293885643
1.6656325
0.0787821709

h1 change in forward
[[0.09040787 0.        ]
 [0.1820838  1.        ]]
minimum
-3.9328582679524136
-0.64594835
0.01016279871284816
h1 change in forward
[[0.09040787 0.0101628 ]
 [0.1820838  0.1882642 ]]
outchange in forward
[[0.46450815]
 [0.88361034]]
after fwd
[[0.03529412 0.40392157 0.60392157]
 [0.43529412 0.50392157 0.60392157]]
[[0.09040787 0.0101628 ]
 [0.1820838  0.1882642 ]]
[[0.46450815]
 [0.88361034]]
consistency detected
try decreasing
input interval
[[0.03529412 0.40392157 0.60392157]
 [0.43529412 0.40392157 0.60392157]]
input before fwd
input
[[0.03529412 0.40392157 0.50392157]
 [0.43529412 0.40392157 0.60392157]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.1926937809177476
1.6656325
0.17842406040527262
h1 change in forward
[[0.17842406 0.        ]
 [0.18301815 1.        ]]
minimum
-3.932858267952414
-0.64594835
0.01016279871284816
h1 change in forward
[[0.17842406 0.0101628 ]
 [0.18301815 0.29487362]]
outchange in forward
[[0.24698225]
 [0.81686364]]
after fwd
[[0.035294

 [0.19633588 1.        ]]
minimum
-3.820461101157993
-0.64594835
0.011358005516233394
h1 change in forward
[[0.19245708 0.01135801]
 [0.19633588 0.15987533]]
outchange in forward
[[0.50728853]
 [0.80212159]]
after fwd
[[0.03137255 0.39215686 0.58431373]
 [0.43137255 0.39215686 0.58431373]]
[[0.19245708 0.01135801]
 [0.19633588 0.15987533]]
[[0.50728853]
 [0.80212159]]
before bkw
[[0.03137255 0.39215686 0.58431373]
 [0.43137255 0.39215686 0.58431373]]
[[0.19245708 0.01135801]
 [0.19633588 0.15987533]]
[[0.50728853]
 [0.80212159]]
[-1.26592178]
[-2.63637308]
[-1.26592178]
[-2.63637308]
[-1.92178236 -0.24614603]
[-15.48114204 -13.16956121]
[-1.92178236 -0.24614603]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.23786598 0.11182745]
 [1.         1.         1.        ]]
[[1.0000000e-06 1.0000000e-06]
 [4.3631039e-01 2.9067781e-01]]
[[0.50728853]
 [0.80212159]]
try increasing
input interval
[[0.03137255 0.39215686 0.58431373]
 [0.43137255 0.39215686 0.58431373]]
input before fwd
input


[-2.4205858 -0.6608774]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.30168393 0.17973976]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.19742958e-01 2.13018496e-01]]
[[0.67557421]
 [0.82884566]]
input before fwd
input
[[0.         0.30168393 0.17973976]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.19742958e-01 2.13018496e-01]]
[[0.67557421]
 [0.82884566]]
minimum
-7.878649845719338
1.6656325
0.0019991792859070604
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [3.44868433e-01 2.13018496e-01]]
minimum
-8.06133194610298
-0.64594835
0.00016535007577270547
h1 change in forward
[[1.99917929e-03 1.65350076e-04]
 [3.44868433e-01 9.99613221e-01]]
outchange in forward
[[2.06594134e-04]
 [9.34131056e-01]]
after fwd
[[0.         0.30168393 0.17973976]
 [1.         1.         1.        ]]
[[1.99917929e-03 1.65350076e-04]
 [3.44868433e-01 9.99613221e-01]]
[[2.06594134e-04]
 [9.34131056e-01]]
consistency detected
try increasing


outchange in forward
[[0.88532642]
 [0.89785433]]
after fwd
[[0.29607843 0.56078431 0.82352941]
 [0.39607843 0.56078431 0.82352941]]
[[0.06004665 0.01423348]
 [0.06039709 0.02830483]]
[[0.88532642]
 [0.89785433]]
before bkw
[[0.29607843 0.56078431 0.82352941]
 [0.39607843 0.56078431 0.82352941]]
[[0.06004665 0.01423348]
 [0.06039709 0.02830483]]
[[0.88532642]
 [0.89785433]]
[-0.49192137]
[-0.6216625]
[-0.49192137]
[-0.6216625]
[-3.83122702 -1.96334885]
[-15.48114204 -13.16956121]
[-3.83122702 -1.96334885]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.4821643  0.38616285]
 [0.78635755 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.02882938e-01 6.85424597e-02]]
[[0.88532642]
 [0.89785433]]
try decreasing
input interval
[[0.29607843 0.56078431 0.82352941]
 [0.39607843 0.56078431 0.82352941]]
input before fwd
input
[[0.19607843 0.56078431 0.82352941]
 [0.39607843 0.56078431 0.82352941]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.422533141748578
1.6656325
0.059698108106

minimum
-6.819168167323368
-0.64594835
0.0005723905200646983
h1 change in forward
[[9.21644500e-04 5.72390520e-04]
 [1.16921309e-01 9.97111268e-01]]
outchange in forward
[[8.37290223e-04]
 [9.34304308e-01]]
after fwd
[[0.1        0.47586434 0.27874486]
 [0.79586037 1.1        1.        ]]
[[9.21644500e-04 5.72390520e-04]
 [1.16921309e-01 9.97111268e-01]]
[[8.37290223e-04]
 [9.34304308e-01]]
consistency detected
try increasing
input interval
[[0.1        0.47586434 0.37874486]
 [0.79586037 1.1        1.        ]]
rule generate
[[0.1        0.47586434 0.37874486]
 [0.79586037 1.1        1.1       ]]
testing this data point
[[0.45882353 0.46666667 0.67843137]
 [0.45882353 0.46666667 0.67843137]]
try decreasing
input interval
[[0.45882353 0.46666667 0.67843137]
 [0.45882353 0.46666667 0.67843137]]
input before fwd
input
[[0.35882353 0.46666667 0.67843137]
 [0.45882353 0.46666667 0.67843137]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.6677437500626437
1.6656325
0.1189814310273504
h1 change 

[-2.03443523 -0.3366823 ]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.25227902 0.12681835]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.08830352e-01 2.72370116e-01]]
[[0.54864619]
 [0.86497105]]
try increasing
input interval
[[0.03529412 0.45882353 0.66666667]
 [0.53529412 0.45882353 0.66666667]]
input before fwd
input
[[0.03529412 0.45882353 0.66666667]
 [0.63529412 0.45882353 0.66666667]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.625738189267177
1.6656325
0.12345560853978685
h1 change in forward
[[0.12345561 0.        ]
 [0.12753263 1.        ]]
minimum
-4.327070955201691
-0.64594835
0.0068746285000167
h1 change in forward
[[0.12345561 0.00687463]
 [0.12753263 0.31818202]]
outchange in forward
[[0.27073309]
 [0.86497105]]
after fwd
[[0.03529412 0.45882353 0.66666667]
 [0.63529412 0.45882353 0.66666667]]
[[0.12345561 0.00687463]
 [0.12753263 0.31818202]]
[[0.27073309]
 [0.86497105]]
consistency detected
try decreasing
input interval
[[0.03529412 

 [0.00828369 0.17133323]]
outchange in forward
[[0.74298231]
 [0.85478837]]
after fwd
[[0.68039216 0.82352941 0.99607843]
 [0.78039216 0.82352941 0.99607843]]
[[0.00823298 0.09295967]
 [0.00828369 0.17133323]]
[[0.74298231]
 [0.85478837]]
before bkw
[[0.68039216 0.82352941 0.99607843]
 [0.78039216 0.82352941 0.99607843]]
[[0.00823298 0.09295967]
 [0.00828369 0.17133323]]
[[0.74298231]
 [0.85478837]]
[-0.89286752]
[-1.60400195]
[-0.89286752]
[-1.60400195]
[-2.68343005 -0.89187464]
[-15.48114204 -13.16956121]
[-2.68343005 -0.89187464]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.33531277 0.21690659]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.65456631e-01 1.76851971e-01]]
[[0.74298231]
 [0.85478837]]
input before fwd
input
[[0.         0.33531277 0.21690659]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.65456631e-01 1.76851971e-01]]
[[0.74298231]
 [0.85478837]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 

outchange in forward
[[0.87648886]
 [0.90264277]]
after fwd
[[0.40980392 0.67058824 0.8627451 ]
 [0.50980392 0.67058824 0.8627451 ]]
[[0.02648452 0.03071296]
 [0.02664464 0.06008311]]
[[0.87648886]
 [0.90264277]]
before bkw
[[0.40980392 0.67058824 0.8627451 ]
 [0.50980392 0.67058824 0.8627451 ]]
[[0.02648452 0.03071296]
 [0.02664464 0.06008311]]
[[0.87648886]
 [0.90264277]]
[-0.43858941]
[-0.70593665]
[-0.43858941]
[-0.70593665]
[-3.68843021 -1.82619508]
[-15.48114204 -13.16956121]
[-3.68843021 -1.82619508]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.46389458 0.36467879]
 [0.81387975 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.16830010e-01 7.78342491e-02]]
[[0.87648886]
 [0.90264277]]
input before fwd
input
[[0.         0.46389458 0.36467879]
 [0.81387975 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.16830010e-01 7.78342491e-02]]
[[0.87648886]
 [0.90264277]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.9991

h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [2.59827988e-01 1.59584758e-01]]
minimum
-7.902466146549209
-0.64594835
0.0001938146378998154
h1 change in forward
[[1.99917929e-03 1.93814638e-04]
 [2.59827988e-01 9.99246667e-01]]
outchange in forward
[[3.46468311e-04]
 [9.34115169e-01]]
after fwd
[[0.         0.35289387 0.23664026]
 [0.97790381 1.         1.        ]]
[[1.99917929e-03 1.93814638e-04]
 [2.59827988e-01 9.99246667e-01]]
[[3.46468311e-04]
 [9.34115169e-01]]
consistency detected
try increasing
input interval
[[0.1        0.35289387 0.23664026]
 [0.97790381 1.         1.        ]]
try decreasing
input interval
[[0.1        0.35289387 0.23664026]
 [1.07790381 1.         1.        ]]
input before fwd
input
[[0.1        0.25289387 0.23664026]
 [1.07790381 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770112
1.6656325
0.002011571860831458
h1 change in forward
[[0.00201157 0.        ]
 [0.43559308 1.        ]]
minimum
-7.510877339443191
-0.645

after bkw
[[0.         0.32796687 0.20871961]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.76801770e-01 1.84410306e-01]]
[[0.72967517]
 [0.88876524]]
try increasing
input interval
[[0.03921569 0.50196078 0.74117647]
 [0.53921569 0.50196078 0.74117647]]
input before fwd
input
[[0.03921569 0.50196078 0.74117647]
 [0.63921569 0.50196078 0.74117647]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.9673230218536712
1.6656325
0.0909830483398338
h1 change in forward
[[0.09098305 0.        ]
 [0.09410282 1.        ]]
minimum
-4.836108316159716
-0.64594835
0.004143523367493496
h1 change in forward
[[0.09098305 0.00414352]
 [0.09410282 0.21905592]]
outchange in forward
[[0.52750695]
 [0.88876524]]
after fwd
[[0.03921569 0.50196078 0.74117647]
 [0.63921569 0.50196078 0.74117647]]
[[0.09098305 0.00414352]
 [0.09410282 0.21905592]]
[[0.52750695]
 [0.88876524]]
before bkw
[[0.03921569 0.50196078 0.74117647]
 [0.63921569 0.50196078 0.74117647]]
[[0.09098305 0.00414352]
 [0.094

outchange in forward
[[0.8733692 ]
 [0.90368384]]
after fwd
[[0.54705882 0.72941176 0.97254902]
 [0.64705882 0.72941176 0.97254902]]
[[0.01691497 0.03577592]
 [0.01701825 0.06963981]]
[[0.8733692 ]
 [0.90368384]]
before bkw
[[0.54705882 0.72941176 0.97254902]
 [0.64705882 0.72941176 0.97254902]]
[[0.01691497 0.03577592]
 [0.01701825 0.06963981]]
[[0.8733692 ]
 [0.90368384]]
[-0.42668582]
[-0.73444668]
[-0.42668582]
[-0.73444668]
[-3.64348152 -1.78318862]
[-15.48114204 -13.16956121]
[-3.64348152 -1.78318862]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.45814375 0.35793456]
 [0.82251946 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.21548319e-01 8.09776713e-02]]
[[0.8733692 ]
 [0.90368384]]
input before fwd
input
[[0.         0.45814375 0.35793456]
 [0.82251946 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.21548319e-01 8.09776713e-02]]
[[0.8733692 ]
 [0.90368384]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.9991

[-2.04848346 -0.34811091]
[-15.48114204 -13.16956121]
[-2.04848346 -0.34811091]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.25407638 0.12870311]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.05439461e-01 2.70111044e-01]]
[[0.55371478]
 [0.77951763]]
try increasing
input interval
[[0.03137255 0.36078431 0.54117647]
 [0.33137255 0.36078431 0.84117647]]
rule generate
[[0.03137255 0.36078431 0.54117647]
 [0.33137255 0.36078431 0.94117647]]
testing this data point
[[0.58431373 0.74509804 0.99215686]
 [0.58431373 0.74509804 0.99215686]]
try decreasing
input interval
[[0.58431373 0.74509804 0.99215686]
 [0.58431373 0.74509804 0.99215686]]
input before fwd
input
[[0.48431373 0.74509804 0.99215686]
 [0.58431373 0.74509804 0.99215686]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-5.855846418937047
1.6656325
0.014917153805232064
h1 change in forward
[[0.01491715 0.        ]
 [0.01500842 1.        ]]
minimum
-3.2162075295167805
-0.64594835
0.020589777137327347
h1 c

-3.756449629746231
-0.64594835
0.012099737564993671
h1 change in forward
[[0.23954444 0.01209974]
 [0.41217077 0.12060289]]
outchange in forward
[[0.28519855]
 [0.75182292]]
after fwd
[[0.00980392 0.25686275 0.51372549]
 [0.30980392 0.35686275 0.51372549]]
[[0.23954444 0.01209974]
 [0.41217077 0.12060289]]
[[0.28519855]
 [0.75182292]]
consistency detected
try increasing
input interval
[[0.00980392 0.35686275 0.51372549]
 [0.30980392 0.35686275 0.51372549]]
input before fwd
input
[[0.00980392 0.35686275 0.51372549]
 [0.30980392 0.45686275 0.51372549]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.6024148813649717
1.6656325
0.12600177010884933
h1 change in forward
[[0.12600177 0.        ]
 [0.24294471 1.        ]]
minimum
-3.446225072823318
-0.64594835
0.01642848836587077
h1 change in forward
[[0.12600177 0.01642849]
 [0.24294471 0.15755832]]
outchange in forward
[[0.44239206]
 [0.8526038 ]]
after fwd
[[0.00980392 0.35686275 0.51372549]
 [0.30980392 0.45686275 0.51372549]]
[[0.12600177 0.01

[-3.68843021 -1.82619508]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.46389458 0.36467879]
 [0.81387975 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.16830010e-01 7.78342491e-02]]
[[0.87648886]
 [0.90264277]]
input before fwd
input
[[0.         0.46389458 0.36467879]
 [0.81387975 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.16830010e-01 7.78342491e-02]]
[[0.87648886]
 [0.90264277]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [1.26460660e-01 7.78342491e-02]]
minimum
-7.558114670140387
-0.64594835
0.00027346510718879107
h1 change in forward
[[1.99917929e-03 2.73465107e-04]
 [1.26460660e-01 9.92513323e-01]]
outchange in forward
[[8.24061661e-04]
 [9.34070695e-01]]
after fwd
[[0.         0.46389458 0.36467879]
 [0.81387975 1.         1.        ]]
[[1.99917929e-03 2.73465107e-04]
 [1.26460660e-01 9.92513323e-01]]
[[8.24061661e-04]
 [9.34070695e-01]]
consistency detected
try increasi

after bkw
[[0.         0.24295013 0.11709002]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.26563055e-01 2.84183961e-01]]
[[0.52199922]
 [0.8771567 ]]
try decreasing
input interval
[[0.05686275 0.3745098  0.72941176]
 [0.55686275 0.4745098  0.72941176]]
input before fwd
input
[[0.05686275 0.2745098  0.72941176]
 [0.55686275 0.4745098  0.72941176]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.7509358002274644
1.6656325
0.11053348903505869
h1 change in forward
[[0.11053349 0.        ]
 [0.37962613 1.        ]]
minimum
-5.312017935397578
-0.64594835
0.0025784982732323866
h1 change in forward
[[0.11053349 0.0025785 ]
 [0.37962613 0.13842298]]
outchange in forward
[[0.29239212]
 [0.87806715]]
after fwd
[[0.05686275 0.2745098  0.72941176]
 [0.55686275 0.4745098  0.72941176]]
[[0.11053349 0.0025785 ]
 [0.37962613 0.13842298]]
[[0.29239212]
 [0.87806715]]
consistency detected
try increasing
input interval
[[0.05686275 0.3745098  0.72941176]
 [0.55686275 0.4745098  0.7

outchange in forward
[[0.00109496]
 [0.9338533 ]]
after fwd
[[0.1        0.51877035 0.42944104]
 [0.83091591 1.         1.        ]]
[[2.01157186e-03 6.53828433e-04]
 [8.59175219e-02 9.88155735e-01]]
[[0.00109496]
 [0.9338533 ]]
consistency detected
try decreasing
input interval
[[0.1        0.51877035 0.42944104]
 [0.73091591 1.         1.        ]]
input before fwd
input
[[0.1        0.41877035 0.42944104]
 [0.73091591 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770111
1.6656325
0.0020115718608314597
h1 change in forward
[[0.00201157 0.        ]
 [0.16950754 1.        ]]
minimum
-6.996287739852985
-0.64594835
0.000479524423439607
h1 change in forward
[[2.01157186e-03 4.79524423e-04]
 [1.69507537e-01 9.76389802e-01]]
outchange in forward
[[7.35435394e-04]
 [9.33950891e-01]]
after fwd
[[0.1        0.41877035 0.42944104]
 [0.73091591 1.         1.        ]]
[[2.01157186e-03 4.79524423e-04]
 [1.69507537e-01 9.76389802e-01]]
[[7.35435394e-04]
 [9.33950891e-

h1 change in forward
[[9.15960415e-04 0.00000000e+00]
 [2.39278660e-02 1.00000000e+00]]
minimum
-6.868171289480373
-0.64594835
0.0005450326694440011
h1 change in forward
[[9.15960415e-04 5.45032669e-04]
 [2.39278660e-02 6.51277369e-01]]
outchange in forward
[[0.03273678]
 [0.93432164]]
after fwd
[[0.         0.68629586 0.52989097]
 [0.37412905 1.1        1.        ]]
[[9.15960415e-04 5.45032669e-04]
 [2.39278660e-02 6.51277369e-01]]
[[0.03273678]
 [0.93432164]]
consistency detected
try increasing
input interval
[[0.         0.68629586 0.62989097]
 [0.37412905 1.1        1.        ]]
rule generate
[[0.         0.68629586 0.62989097]
 [0.37412905 1.1        1.1       ]]
testing this data point
[[0.61176471 0.68627451 0.8627451 ]
 [0.61176471 0.68627451 0.8627451 ]]
try decreasing
input interval
[[0.61176471 0.68627451 0.8627451 ]
 [0.61176471 0.68627451 0.8627451 ]]
input before fwd
input
[[0.51176471 0.68627451 0.8627451 ]
 [0.61176471 0.68627451 0.8627451 ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [

[-1.37185956]
[-1.54939412]
[-2.73029617 -0.93380024]
[-15.48114204 -13.16956121]
[-2.73029617 -0.93380024]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.34130892 0.22361536]
 [0.99458939 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.56419228e-01 1.70831091e-01]]
[[0.75327112]
 [0.78476767]]
try decreasing
input interval
[[0.1        0.38823529 0.57647059]
 [0.2        0.38823529 0.57647059]]
try increasing
input interval
[[0.         0.38823529 0.57647059]
 [0.2        0.38823529 0.57647059]]
input before fwd
input
[[0.         0.38823529 0.57647059]
 [0.3        0.38823529 0.57647059]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.0705559437765797
1.6656325
0.19703599532774194
h1 change in forward
[[0.197036   0.        ]
 [0.19999156 1.        ]]
minimum
-3.982237005233764
-0.64594835
0.009677899544560196
h1 change in forward
[[0.197036   0.0096779 ]
 [0.19999156 0.07427896]]
outchange in forward
[[0.68641331]
 [0.80014132]]
after fwd
[[0.         0.38823529 0.576

after bkw
[[0.         0.35986253 0.24451315]
 [0.96781823 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [2.29757787e-01 1.53068760e-01]]
[[0.78197873]
 [0.88372008]]
try increasing
input interval
[[0.03137255 0.48627451 0.77647059]
 [0.53137255 0.48627451 0.77647059]]
input before fwd
input
[[0.03137255 0.48627451 0.77647059]
 [0.63137255 0.48627451 0.77647059]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.8474140563431907
1.6656325
0.10139848157161059
h1 change in forward
[[0.10139848 0.        ]
 [0.1048342  1.        ]]
minimum
-5.257364456326354
-0.64594835
0.002722949882775706
h1 change in forward
[[0.10139848 0.00272295]
 [0.1048342  0.15545619]]
outchange in forward
[[0.65070252]
 [0.88372008]]
after fwd
[[0.03137255 0.48627451 0.77647059]
 [0.63137255 0.48627451 0.77647059]]
[[0.10139848 0.00272295]
 [0.1048342  0.15545619]]
[[0.65070252]
 [0.88372008]]
before bkw
[[0.03137255 0.48627451 0.77647059]
 [0.63137255 0.48627451 0.77647059]]
[[0.10139848 0.00272295]
 [0.10

minimum
-8.252440805091954
-0.64594835
0.0001365901454620404
h1 change in forward
[[1.99917929e-03 1.36590145e-04]
 [4.61061555e-01 9.99785653e-01]]
outchange in forward
[[1.02228278e-04]
 [9.34147104e-01]]
after fwd
[[0.         0.24008053 0.11411625]
 [1.         1.         1.        ]]
[[1.99917929e-03 1.36590145e-04]
 [4.61061555e-01 9.99785653e-01]]
[[1.02228278e-04]
 [9.34147104e-01]]
consistency detected
try decreasing
input interval
[[0.         0.24008053 0.11411625]
 [0.9        1.         1.        ]]
input before fwd
input
[[0.         0.14008053 0.11411625]
 [0.9        1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[0.00199918 0.        ]
 [0.65006883 1.        ]]
minimum
-8.562665362014865
-0.64594835
0.00010016278151887496
h1 change in forward
[[1.99917929e-03 1.00162782e-04]
 [6.50068826e-01 9.99567669e-01]]
outchange in forward
[[3.26940319e-05]
 [9.34167425e-01]]
after fwd
[[0. 

 [1.]]
minimum
-4.495733964209463
1.6656325
0.05571905848633863
h1 change in forward
[[0.05571906 0.        ]
 [0.22731244 1.        ]]
minimum
-6.238388211119409
-0.64594835
0.001022648208851418
h1 change in forward
[[0.05571906 0.00102265]
 [0.22731244 0.20567525]]
outchange in forward
[[0.36045014]
 [0.91048538]]
after fwd
[[0.00392157 0.36862745 0.82352941]
 [0.70392157 0.56862745 0.82352941]]
[[0.05571906 0.00102265]
 [0.22731244 0.20567525]]
[[0.36045014]
 [0.91048538]]
consistency detected
try increasing
input interval
[[0.00392157 0.46862745 0.82352941]
 [0.70392157 0.56862745 0.82352941]]
input before fwd
input
[[0.00392157 0.46862745 0.82352941]
 [0.70392157 0.66862745 0.82352941]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-5.277337634329703
1.6656325
0.026295625451209653
h1 change in forward
[[0.02629563 0.        ]
 [0.11866295 1.        ]]
minimum
-5.928163654196496
-0.64594835
0.0013940988249058458
h1 change in forward
[[0.02629563 0.0013941 ]
 [0.11866295 0.260963  ]]
outc

h1 change in forward
[[0.06336397 0.        ]
 [0.06410295 1.        ]]
minimum
-4.031514593199188
-0.64594835
0.009216844674087126
h1 change in forward
[[0.06336397 0.00921684]
 [0.06410295 0.03647975]]
outchange in forward
[[0.87515521]
 [0.90016532]]
after fwd
[[0.21176471 0.55294118 0.80392157]
 [0.41176471 0.55294118 0.80392157]]
[[0.06336397 0.00921684]
 [0.06410295 0.03647975]]
[[0.87515521]
 [0.90016532]]
before bkw
[[0.21176471 0.55294118 0.80392157]
 [0.41176471 0.55294118 0.80392157]]
[[0.06336397 0.00921684]
 [0.06410295 0.03647975]]
[[0.87515521]
 [0.90016532]]
[-0.46646648]
[-0.71819924]
[-0.46646648]
[-0.71819924]
[-3.66890816 -1.80750632]
[-15.48114204 -13.16956121]
[-3.66890816 -1.80750632]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.46139689 0.36174851]
 [0.81763359 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.18859426e-01 7.91862823e-02]]
[[0.87515521]
 [0.90016532]]
try decreasing
input interval
[[0.21176471 0.55294118 0.80392157]
 [0.411764

 [0.73921569 0.53333333 0.74509804]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.212777558144401
1.6656325
0.07261851625769879
h1 change in forward
[[0.07261852 0.        ]
 [0.0755922  1.        ]]
minimum
-4.774066218207864
-0.64594835
0.004407569478639778
h1 change in forward
[[0.07261852 0.00440757]
 [0.0755922  0.37582175]]
outchange in forward
[[0.23150409]
 [0.8990544 ]]
after fwd
[[0.03921569 0.53333333 0.74509804]
 [0.73921569 0.53333333 0.74509804]]
[[0.07261852 0.00440757]
 [0.0755922  0.37582175]]
[[0.23150409]
 [0.8990544 ]]
consistency detected
try decreasing
input interval
[[0.03921569 0.53333333 0.74509804]
 [0.63921569 0.53333333 0.74509804]]
input before fwd
input
[[0.03921569 0.43333333 0.74509804]
 [0.63921569 0.53333333 0.74509804]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.212777558144401
1.6656325
0.07261851625769879
h1 change in forward
[[0.07261852 0.        ]
 [0.1507938  1.        ]]
minimum
-5.084290775130777
-0.64594835
0.003235796498297192
h1 change in for

outchange in forward
[[0.85149785]
 [0.86654353]]
after fwd
[[0.15490196 0.4745098  0.69019608]
 [0.25490196 0.4745098  0.69019608]]
[[0.11137453 0.01343147]
 [0.11198884 0.02673146]]
[[0.85149785]
 [0.86654353]]
before bkw
[[0.15490196 0.4745098  0.69019608]
 [0.25490196 0.4745098  0.69019608]]
[[0.11137453 0.01343147]
 [0.11198884 0.02673146]]
[[0.85149785]
 [0.86654353]]
[-0.79479229]
[-0.9191317]
[-0.79479229]
[-0.9191317]
[-3.38375592 -1.53647046]
[-15.48114204 -13.16956121]
[-3.38375592 -1.53647046]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.42491392 0.31916244]
 [0.87218858 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.52113035e-01 1.01340433e-01]]
[[0.85149785]
 [0.86654353]]
try decreasing
input interval
[[0.15490196 0.4745098  0.69019608]
 [0.25490196 0.4745098  0.69019608]]
try increasing
input interval
[[0.05490196 0.4745098  0.69019608]
 [0.25490196 0.4745098  0.69019608]]
input before fwd
input
[[0.05490196 0.4745098  0.69019608]
 [0.35490196 0.47

minimum
-6.151943250730926
-0.64594835
0.0011148815591806751
h1 change in forward
[[0.10953575 0.00111488]
 [0.11384957 0.18401497]]
outchange in forward
[[0.57655159]
 [0.88011883]]
after fwd
[[0.05490196 0.4745098  0.69019608]
 [0.55490196 0.4745098  0.89019608]]
[[0.10953575 0.00111488]
 [0.11384957 0.18401497]]
[[0.57655159]
 [0.88011883]]
before bkw
[[0.05490196 0.4745098  0.69019608]
 [0.55490196 0.4745098  0.89019608]]
[[0.10953575 0.00111488]
 [0.11384957 0.18401497]]
[[0.57655159]
 [0.88011883]]
[-0.67197333]
[-2.3568961]
[-0.67197333]
[-2.3568961]
[-2.11270116 -0.40072927]
[-15.48114204 -13.16956121]
[-2.11270116 -0.40072927]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.26229253 0.13736041]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.90057941e-01 2.59863599e-01]]
[[0.57655159]
 [0.88011883]]
try increasing
input interval
[[0.05490196 0.4745098  0.69019608]
 [0.55490196 0.4745098  0.89019608]]
rule generate
[[0.05490196 0.4745098  0.690196

after bkw
[[0.         0.26881544 0.14428088]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.77998571e-01 2.51829431e-01]]
[[0.59423507]
 [0.75246941]]
try increasing
input interval
[[0.04901961 0.35686275 0.58039216]
 [0.34901961 0.35686275 0.58039216]]
input before fwd
input
[[0.04901961 0.35686275 0.58039216]
 [0.44901961 0.35686275 0.58039216]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-2.82255714050695
1.6656325
0.23922654055108292
h1 change in forward
[[0.23922654 0.        ]
 [0.2437634  1.        ]]
minimum
-3.7708194508272066
-0.64594835
0.01192916909266654
h1 change in forward
[[0.23922654 0.01192917]
 [0.2437634  0.16665605]]
outchange in forward
[[0.42093884]
 [0.75246941]]
after fwd
[[0.04901961 0.35686275 0.58039216]
 [0.44901961 0.35686275 0.58039216]]
[[0.23922654 0.01192917]
 [0.2437634  0.16665605]]
[[0.42093884]
 [0.75246941]]
consistency detected
try decreasing
input interval
[[0.04901961 0.35686275 0.58039216]
 [0.34901961 0.35686275 0.5803

minimum
-7.8786498457193375
1.6656325
0.001999179285907062
h1 change in forward
[[1.99917929e-03 1.00000000e-06]
 [4.60293324e-02 2.87645375e-02]]
minimum
-7.131224437411596
-0.64594835
0.0004190200045360287
h1 change in forward
[[1.99917929e-03 4.19020005e-04]
 [4.60293324e-02 8.75225727e-01]]
outchange in forward
[[0.00386981]
 [0.93398935]]
after fwd
[[0.         0.60150143 0.52807484]
 [0.60456085 1.         1.        ]]
[[1.99917929e-03 4.19020005e-04]
 [4.60293324e-02 8.75225727e-01]]
[[0.00386981]
 [0.93398935]]
consistency detected
try increasing
input interval
[[0.1        0.60150143 0.52807484]
 [0.60456085 1.         1.        ]]
input before fwd
input
[[0.1        0.60150143 0.52807484]
 [0.70456085 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770111
1.6656325
0.0020115718608314597
h1 change in forward
[[0.00201157 0.        ]
 [0.046302   1.        ]]
minimum
-6.429411073382665
-0.64594835
0.0008449739538251375
h1 change in forward
[[2.011571

[-0.37187746]
[-0.50283633]
[-0.37187746]
[-0.50283633]
[-4.0650434  -2.18944893]
[-15.48114204 -13.16956121]
[-4.0650434  -2.18944893]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.51207926 0.42150986]
 [0.74107617 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [8.32176284e-02 5.54410772e-02]]
[[0.89684894]
 [0.90834992]]
try decreasing
input interval
[[0.18039216 0.57254902 0.8627451 ]
 [0.38039216 0.57254902 0.8627451 ]]
try increasing
input interval
[[0.08039216 0.57254902 0.8627451 ]
 [0.38039216 0.57254902 0.8627451 ]]
input before fwd
input
[[0.08039216 0.57254902 0.8627451 ]
 [0.48039216 0.57254902 0.8627451 ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.524105359234062
1.6656325
0.05424499256850187
h1 change in forward
[[0.05424499 0.        ]
 [0.0555298  1.        ]]
minimum
-5.42192515298432
-0.64594835
0.002310741249837702
h1 change in forward
[[0.05424499 0.00231074]
 [0.0555298  0.03694714]]
outchange in forward
[[0.88025989]
 [0.91025889]]
after fwd
[[0

minimum
-3.5031228371694976
1.6656325
0.1373483748042074
h1 change in forward
[[0.13734837 0.        ]
 [0.14105806 1.        ]]
minimum
-4.344688988666909
-0.64594835
0.006755382781630433
h1 change in forward
[[0.13734837 0.00675538]
 [0.14105806 0.18519032]]
outchange in forward
[[0.5333424 ]
 [0.85499685]]
after fwd
[[0.01960784 0.44313725 0.65098039]
 [0.51960784 0.44313725 0.65098039]]
[[0.13734837 0.00675538]
 [0.14105806 0.18519032]]
[[0.5333424 ]
 [0.85499685]]
before bkw
[[0.01960784 0.44313725 0.65098039]
 [0.51960784 0.44313725 0.65098039]]
[[0.13734837 0.00675538]
 [0.14105806 0.18519032]]
[[0.5333424 ]
 [0.85499685]]
[-0.89118693]
[-2.53196145]
[-0.89118693]
[-2.53196145]
[-1.99238648 -0.30265529]
[-15.48114204 -13.16956121]
[-1.99238648 -0.30265529]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.24689922 0.12119697]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.19030634e-01 2.79165727e-01]]
[[0.5333424 ]
 [0.85499685]]
try increasing
inpu

outchange in forward
[[6.81645508e-04]
 [9.34083259e-01]]
after fwd
[[0.         0.43621497 0.33230799]
 [0.85534844 1.         1.        ]]
[[1.99917929e-03 2.50968541e-04]
 [1.52945623e-01 9.95803903e-01]]
[[6.81645508e-04]
 [9.34083259e-01]]
consistency detected
try increasing
input interval
[[0.1        0.43621497 0.33230799]
 [0.85534844 1.         1.        ]]
try decreasing
input interval
[[0.1        0.43621497 0.33230799]
 [0.95534844 1.         1.        ]]
input before fwd
input
[[0.1        0.33621497 0.33230799]
 [0.95534844 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770111
1.6656325
0.0020115718608314597
h1 change in forward
[[0.00201157 0.        ]
 [0.28416662 1.        ]]
minimum
-7.252394804143986
-0.64594835
0.000371220458546775
h1 change in forward
[[2.01157186e-03 3.71220459e-04]
 [2.84166625e-01 9.97915644e-01]]
outchange in forward
[[3.02730433e-04]
 [9.34011459e-01]]
after fwd
[[0.1        0.33621497 0.33230799]
 [0.95534844 1.  

h1 change in forward
[[0.06670438 0.00393545]
 [0.06747951 0.01582583]]
outchange in forward
[[0.89228081]
 [0.90262867]]
after fwd
[[0.16862745 0.54509804 0.8627451 ]
 [0.36862745 0.54509804 0.8627451 ]]
[[0.06670438 0.00393545]
 [0.06747951 0.01582583]]
[[0.89228081]
 [0.90262867]]
before bkw
[[0.16862745 0.54509804 0.8627451 ]
 [0.36862745 0.54509804 0.8627451 ]]
[[0.06670438 0.00393545]
 [0.06747951 0.01582583]]
[[0.89228081]
 [0.90262867]]
[-0.43874981]
[-0.55127614]
[-0.43874981]
[-0.55127614]
[-3.96428953 -2.09180748]
[-15.48114204 -13.16956121]
[-3.96428953 -2.09180748]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.4991886  0.4062549 ]
 [0.76061857 1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [9.12342453e-02 6.07818913e-02]]
[[0.89228081]
 [0.90262867]]
try decreasing
input interval
[[0.16862745 0.54509804 0.8627451 ]
 [0.36862745 0.54509804 0.8627451 ]]
try increasing
input interval
[[0.06862745 0.54509804 0.8627451 ]
 [0.36862745 0.54509804 0.8627451 ]]
in

minimum
-4.172005712284762
-0.64594835
0.008018492230627153
h1 change in forward
[[0.10799892 0.00801849]
 [0.10859689 0.01604567]]
outchange in forward
[[0.86574048]
 [0.87437721]]
after fwd
[[0.13921569 0.47843137 0.7372549 ]
 [0.23921569 0.47843137 0.7372549 ]]
[[0.10799892 0.00801849]
 [0.10859689 0.01604567]]
[[0.86574048]
 [0.87437721]]
before bkw
[[0.13921569 0.47843137 0.7372549 ]
 [0.23921569 0.47843137 0.7372549 ]]
[[0.10799892 0.00801849]
 [0.10859689 0.01604567]]
[[0.86574048]
 [0.87437721]]
[-0.7253011]
[-0.80171868]
[-0.7253011]
[-0.80171868]
[-3.5430864  -1.68744476]
[-15.48114204 -13.16956121]
[-3.5430864  -1.68744476]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.44529899 0.34290572]
 [0.8417722  1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [1.32681596e-01 8.83948603e-02]]
[[0.86574048]
 [0.87437721]]
try decreasing
input interval
[[0.13921569 0.47843137 0.7372549 ]
 [0.23921569 0.47843137 0.7372549 ]]
try increasing
input interval
[[0.03921569 0.47

minimum
-3.7831707341998237
1.6656325
0.10740384639105222
h1 change in forward
[[0.10740385 0.        ]
 [0.11163736 1.        ]]
minimum
-4.873819076313692
-0.64594835
0.003990789489213165
h1 change in forward
[[0.10740385 0.00399079]
 [0.11163736 0.39911253]]
outchange in forward
[[0.16398394]
 [0.8787189 ]]
after fwd
[[0.03921569 0.47843137 0.6372549 ]
 [0.63921569 0.47843137 0.7372549 ]]
[[0.10740385 0.00399079]
 [0.11163736 0.39911253]]
[[0.16398394]
 [0.8787189 ]]
consistency detected
try increasing
input interval
[[0.03921569 0.47843137 0.7372549 ]
 [0.63921569 0.47843137 0.7372549 ]]
input before fwd
input
[[0.03921569 0.47843137 0.7372549 ]
 [0.63921569 0.47843137 0.8372549 ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.789432048651518
1.6656325
0.10680505894454412
h1 change in forward
[[0.10680506 0.        ]
 [0.11101791 1.        ]]
minimum
-5.773542033924776
-0.64594835
0.0016268355285846998
h1 change in forward
[[0.10680506 0.00162684]
 [0.11101791 0.21267311]]
outchange i

minimum
-3.20892798947353
-0.64594835
0.02073708861384109
h1 change in forward
[[0.12294964 0.02073709]
 [0.23671011 0.10517288]]
outchange in forward
[[0.56987348]
 [0.84999159]]
after fwd
[[0.09215686 0.36078431 0.55294118]
 [0.29215686 0.46078431 0.55294118]]
[[0.12294964 0.02073709]
 [0.23671011 0.10517288]]
[[0.56987348]
 [0.84999159]]
before bkw
[[0.09215686 0.36078431 0.55294118]
 [0.29215686 0.46078431 0.55294118]]
[[0.12294964 0.02073709]
 [0.23671011 0.10517288]]
[[0.56987348]
 [0.84999159]]
[-0.93099414]
[-2.38419427]
[-0.93099414]
[-2.38419427]
[-2.09375105 -0.38513873]
[-15.48114204 -13.16956121]
[-2.09375105 -0.38513873]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.25986801 0.13479869]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.94575692e-01 2.62873406e-01]]
[[0.56987348]
 [0.84999159]]
try increasing
input interval
[[0.09215686 0.36078431 0.55294118]
 [0.29215686 0.46078431 0.55294118]]
input before fwd
input
[[0.09215686 0.36078431 

h1 change in forward
[[1.99917929e-03 2.26586040e-04]
 [1.90201508e-01 9.97884852e-01]]
outchange in forward
[[5.34145219e-04]
 [9.34096874e-01]]
after fwd
[[0.         0.40326231 0.29410897]
 [0.90428339 1.         1.        ]]
[[1.99917929e-03 2.26586040e-04]
 [1.90201508e-01 9.97884852e-01]]
[[5.34145219e-04]
 [9.34096874e-01]]
consistency detected
try increasing
input interval
[[0.1        0.40326231 0.29410897]
 [0.90428339 1.         1.        ]]
try decreasing
input interval
[[0.1        0.40326231 0.29410897]
 [1.00428339 1.         1.        ]]
input before fwd
input
[[0.1        0.30326231 0.29410897]
 [1.00428339 1.         1.        ]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-7.872457730770112
1.6656325
0.002011571860831458
h1 change in forward
[[0.00201157 0.        ]
 [0.34053622 1.        ]]
minimum
-7.354622049710316
-0.64594835
0.00033515896534111906
h1 change in forward
[[2.01157186e-03 3.35158965e-04]
 [3.40536216e-01 9.98950432e-01]]
outchange in forward
[[2.1335081

h1 change in forward
[[0.2687506  0.        ]
 [0.27119135 1.        ]]
minimum
-3.4512931702183742
-0.64594835
0.01634679542898211
h1 change in forward
[[0.2687506  0.0163468 ]
 [0.27119135 0.06335119]]
outchange in forward
[[0.61118516]
 [0.70958359]]
after fwd
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 0.3372549  0.54117647]]
[[0.2687506  0.0163468 ]
 [0.27119135 0.06335119]]
[[0.61118516]
 [0.70958359]]
before bkw
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 0.3372549  0.54117647]]
[[0.2687506  0.0163468 ]
 [0.27119135 0.06335119]]
[[0.61118516]
 [0.70958359]]
[-1.77216673]
[-2.21323254]
[-1.77216673]
[-2.21323254]
[-2.21383245 -0.48479617]
[-15.48114204 -13.16956121]
[-2.21383245 -0.48479617]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.27523147 0.15112737]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [3.66282132e-01 2.44023729e-01]]
[[0.61118516]
 [0.70958359]]
try increasing
input interval
[[0.05294118 0.3372549  0.54117647]
 [0.252941

[-1.91124814 -0.23778368]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.23651821 0.11043714]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.38902929e-01 2.92405007e-01]]
[[0.50337268]
 [0.90147778]]
try increasing
input interval
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 0.5372549  0.74117647]]
input before fwd
input
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 0.5372549  0.84117647]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-4.248594557041047
1.6656325
0.07024303473546264
h1 change in forward
[[0.07024303 0.        ]
 [0.27119135 1.        ]]
minimum
-6.1504620430516255
-0.64594835
0.0011165323087480863
h1 change in forward
[[0.07024303 0.00111653]
 [0.27119135 0.11173246]]
outchange in forward
[[0.50337268]
 [0.90299586]]
after fwd
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 0.5372549  0.84117647]]
[[0.07024303 0.00111653]
 [0.27119135 0.11173246]]
[[0.50337268]
 [0.90299586]]
before bkw
[[0.05294118 0.3372549  0.54117647]
 [0.25294118 

[-1.99911552 -0.30808222]
[-15.48114204 -13.16956121]
after bkw
[[0.         0.24776014 0.12209452]
 [1.         1.         1.        ]]
[[1.00000000e-06 1.00000000e-06]
 [4.17393389e-01 2.78074965e-01]]
[[0.5358038 ]
 [0.87403903]]
try increasing
input interval
[[0.07254902 0.37254902 0.59215686]
 [0.37254902 0.47254902 0.69215686]]
input before fwd
input
[[0.07254902 0.37254902 0.59215686]
 [0.37254902 0.47254902 0.79215686]]
[[0. 0.]
 [1. 1.]]
[[0.]
 [1.]]
minimum
-3.7385675938106044
1.6656325
0.11175534972886565
h1 change in forward
[[0.11175535 0.        ]
 [0.22093388 1.        ]]
minimum
-5.462319893930473
-0.64594835
0.0022194626240423935
h1 change in forward
[[0.11175535 0.00221946]
 [0.22093388 0.13088485]]
outchange in forward
[[0.5358038 ]
 [0.87762464]]
after fwd
[[0.07254902 0.37254902 0.59215686]
 [0.37254902 0.47254902 0.79215686]]
[[0.11175535 0.00221946]
 [0.22093388 0.13088485]]
[[0.5358038 ]
 [0.87762464]]
before bkw
[[0.07254902 0.37254902 0.59215686]
 [0.37254902 

In [132]:


k = 0
            test_val = 0
            while(test_val==0):
                print("testing 1")
                print("input interval")
                print(input_interval)
                test_interval = np.copy(input_interval)
                test_interval[0,k] = test_interval[0,k] - tol
                if(test_interval[0,k]<=0):
                    break
                test_val = test_consistency(input_interval)
                if(test_val== 0):
                    input_interval = np.copy(test_interval)
                else:
                    input_interval[0,k] = input_interval[0,k] + tol
                    break

                #now try increasing the upper bound
                print("try increasing")
                print("input interval")
                print(input_interval)
                test_interval = np.copy(input_interval)
                test_interval[1,k] = test_interval[1,k] + tol
                if(test_interval[1,k]>=1):
                    break
                test_val = test_consistency(input_interval)
                if(test_val==0):
                    input_interval = np.copy(test_interval)
                else:
                    input_interval[1,k] = input_interval[1,k] - tol
                    break
                k = (k + 1)%2
            print("rule generate")
            print(input_interval)
            #rules[t] = input_interval
            #t = t+1
            #print(rules)

IndentationError: unexpected indent (<ipython-input-132-71428b21e63b>, line 4)